services:
  - type: web
    name: pharmcure-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    autoDeploy: true

  - type: static_site
    name: pharmcure-front
    rootDir: front
    buildCommand: npm install && npm run build
    publishPath: build
    plan: free
    autoDeploy: true
