services:
  - type: web
    name: MediEase-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true

  - type: web
    name: MediEase-front
    env: static
    buildCommand: cd front && npm install && npm run build
    staticPublishPath: front/build
    autoDeploy: true
